---
swagger: "2.0"
info:
  version: "0.0.1"
  title: "Backend Portal"
host: "localhost"
basePath: "/portal"
schemes:
  - "http"
paths:
  /member/info:
    get:
      produces:
        - "application/json"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/MemberInfo"
      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:095128183318:function:sam-bookmark-app-listBookmarks/invocations"
        passthroughBehavior: "when_no_match"
  /member/add:
    post:
      tags:
        - "member"
      summary: "Add Member"
      description: "This can only be done by the added member"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "a member object"
          required: true
          schema:
            $ref: "#/definitions/UserData"
      responses:
        "200":
          description: "add success"
          schema:
            $ref: "#/definitions/AddSuccessInfo"
        "400":
          description: "fail to add"
          schema:
            $ref: "#/definitions/AddFailedInfo"
  /member/login:
    post:
      tags:
        - "member"
      summary: "Log in"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "a member object"
          required: true
          schema:
            $ref: "#/definitions/LoginData"
      responses:
        "200":
          description: "200 response"
          schema:
            $ref: "#/definitions/LoginSuccessInfo"
        "400":
          description: "invalid username or password"
          schema:
            $ref: "#/definitions/LoginFailedInfo"

      x-amazon-apigateway-integration:
        type: "aws_proxy"
        httpMethod: "POST"
        uri: "arn:aws:apigateway:us-west-2:lambda:path/2015-03-31/functions/arn:aws:lambda:us-west-2:095128183318:function:sam-bookmark-app-listBookmarks/invocations"
        passthroughBehavior: "when_no_match"
definitions:
  MemberInfo:
    type: "object"
    properties:
      code:
        type: "number"
        example: 200
      message:
        type: "string"
        example: "get member info success"
      data:
        type: "array"
        items:
          type: "object"
          properties:
            id:
              type: "string"
              example: '0000-0000-000000000000-0000'
            nickName:
              type: "string"
              example: 'Chuck'
            grade:
              type: "number"
              example: 2021
            brief:
              type: "string"
              example: "不悔梦归处，只恨太匆匆"
            icon:
              type: "string"
              example: "http://host/any/path/icon.png"
  UserData:
    type: "object"
    properties:
      username:
        type: "string"
        example: 'Chuck'
      loginAccount:
        type: "string"
      grade:
        type: "number"
        example: 2021
      loginPassowrd:
        type: string
      icon:
        type: "string"
        example: "http://host/any/path/icon.png"
      motto:
        type: "string"
        example: "不悔梦归处，只恨太匆匆"
    xml:
      name: "AddMember"

  LoginData:
    type: "object"
    properties:
      loginAccount:
        type: "string"
      loginPassword:
        type: "string"
        example: "123456"
  LoginSuccessInfo:
    type: "object"
    properties:
      code:
        type: "number"
        example: 200
      message:
        type: "string"
        example: "Login success"
      data:
        type: "object"
        properties:
          loginAccount:
            type: "string"
          token:
            type: "string"
          state:
            type: "string"
            example: "success"

  LoginFailedInfo:
    type: "object"
    properties:
      code:
        type: "number"
        example: "400"
      message:
        type: "string"
        example: "login failed with invalid username or password"
      data:
        type: "object"
        properties:
          detail:
            type: "string"
            example: "user doesn't exits / invalid password"

  AddSuccessInfo:
    type: "object"
    properties:
      code:
        type: "number"
        example: "200"
      message:
        type: "string"
        example: "add success"
      data:
        type: "object"
        properties:
          details:
            type: "string"
            example: "add success"

  AddFailedInfo:
    type: "object"
    properties:
      code:
        type: "number"
        example: 400
      message:
        type: "string"
        example: "add failed"
      data:
        type: "object"
        properties:
          details:
            type: "string"
            example: "user exists / invalid username or password"


