name: Auto Run Unit Tests
on: [push, pull_request]
jobs:
  Auto-Run-Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '8'
          cache: 'maven'
      - run: mvn test --file pom.xml
      